### HTTP REQUEST
POST  http://localhost:3000/create_user
Content-Type: application/json

{
    "username": "FefLaRage92i",
    "accountname": "fefounet",
    "password": "testpass1"
}

### get request
GET  http://localhost:3000/time 
Content-Type: application/json

### get request
GET  http://localhost:3000/time_swag 
Content-Type: application/json

### get User 
GET  http://localhost:3000/user/1
Content-Type: application/json

### Add Grid 
POST  http://localhost:3000/add_grid
Content-Type: application/json

{
    "difficulty": "easy"
}

### Get grid 
GET  http://localhost:3000/random_grid
Content-Type: application/json