### HTTP REQUEST
POST  http://localhost:3000/create_user
Content-Type: application/json

{
    "username": "testuser2",
    "password": "testpass1"
}

### get request
GET  http://localhost:3000/time 
Content-Type: application/json

### get request
GET  http://localhost:3000/time_swag 
Content-Type: application/json

### get User 
GET  http://localhost:3000/user/1
Content-Type: application/json

### get grid
GET  http://localhost:3000/grid/1
Content-Type: application/json